all:
	python ./main.py --debug
push:
	python ./tools/auto_docs.py
	python ./tools/update_version.py
	python ./tools/git_automation.py
info:
	python ./tools/code_statistics.py
doc:
	python ./tools/auto_docs.py